#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod aggregator_v3_interface;
pub mod attestation_service_error_lib;
pub mod attestation_service_structs;
pub mod core_legacy_oracle_adapter;
pub mod core_switchboard;
pub mod core_switchboard_attestation_service;
pub mod core_switchboard_v3;
pub mod error_lib;
pub mod i_attestation_service_events;
pub mod i_switchboard;
pub mod i_switchboard_attestation_service;
pub mod i_switchboard_events;
pub mod initializable;
pub mod legacy_oracle_adapter;
pub mod permissions;
pub mod shared_types;
pub mod sort_lib;
pub mod std_invariant;
pub mod std_style;
pub mod switchboard;
pub mod switchboard_attestation_service;
pub mod switchboard_structs;
pub mod switchboard_v2test;
